# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
- group: kvdevops1

stages:
- stage: start_aci
  displayName: Build Prep
  pool:
    vmImage: ubuntu-latest
  jobs:
  - job: start_aci
    displayName: Start build agent
    steps:
    - task: AzureCLI@2
      displayName: Start Azure Container Instance
      inputs:
        azureSubscription: 'terraform'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az container start -n $(ACINAME) -g $(RGNAME)'
- stage: terraform_plan
  displayName: Terraform Plan
  dependsOn: start_aci
  condition: eq(variables.destroy, false)
  pool:
    name: Contoso
    demands:
      - agent.name -equals acicontoso
  jobs:
  - job: terraform_plan
    displayName: Terraform Plan
    steps:
    - script: |
        export ARM_CLIENT_ID=$(client-id) 
        export ARM_CLIENT_SECRET=$(client-secret)
        export ARM_SUBSCRIPTION_ID=$(main-subscription-id)
        export ARM_TENANT_ID=$(tenant-id)
        terraform init \
          -backend-config="resource_group_name=rg-devops" \
          -backend-config="storage_account_name=satfstate98722" \
          -backend-config="container_name=cloudops-network-tfstate" \
          -backend-config="key=terraform.tfstate"
        terraform plan -var="digicert_ssl_validation_key=$(digicert-ssl-validation-key)" -var="vpn_preshared_key=$(vpn-preshared-key)" -out=$(System.DefaultWorkingDirectory)/$(Build.BuildId).tfplan
      displayName: Terraform init and plan
    - task: PublishPipelineArtifact@1
      displayName: Publish $(Build.BuildId).tfplan
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)/$(Build.BuildId).tfplan
        artifactName: $(Build.BuildId).tfplan
- stage: terraform_apply
  displayName: Terraform Apply
  dependsOn: terraform_plan
  pool:
    name: Contoso
    demands:
      - agent.name -equals acicontoso
  jobs:
  - job: manual_validation
    displayName: Approval Gate
    pool: Server
    steps:
    - task: ManualValidation@0
      inputs:
        notifyUsers: $(notifyUsers)
        instructions: 'Have you looked at the plan output?'
  - job: terraform_apply
    displayName: Terraform Apply
    dependsOn: manual_validation
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: Download $(Build.BuildId).tfplan
      inputs:
        artifactName: $(Build.BuildId).tfplan
        patterns: '**/$(Build.BuildId).tfplan'
        path: $(System.DefaultWorkingDirectory)
    - script: |
        export ARM_CLIENT_ID=$(client-id) 
        export ARM_CLIENT_SECRET=$(client-secret)
        export ARM_SUBSCRIPTION_ID=$(main-subscription-id)
        export ARM_TENANT_ID=$(tenant-id)
        terraform init \
          -backend-config="resource_group_name=rg-devops" \
          -backend-config="storage_account_name=satfstate98722" \
          -backend-config="container_name=cloudops-network-tfstate" \
          -backend-config="key=terraform.tfstate"
        terraform apply --auto-approve $(System.DefaultWorkingDirectory)/$(Build.BuildId).tfplan
      displayName: Terraform init and apply
- stage: terraform_destroy
  displayName: Terraform Destroy
  dependsOn: start_aci
  condition: eq(variables.destroy, true)
  pool:
    name: Contoso
    demands: 
      - agent.name -equals acicontoso
  jobs: 
  - job: manual_validation
    displayName: Approval Gate
    pool: Server
    steps:
    - task: ManualValidation@0
      inputs:
        notifyUsers: $(notifyUsers)
        instructions: 'Are you sure you want to destroy everything?'
  - job: terraform_destroy
    displayName: terraform destroy
    dependsOn: manual_validation
    steps: 
    - script: |
        export ARM_CLIENT_ID=$(client-id) 
        export ARM_CLIENT_SECRET=$(client-secret)
        export ARM_SUBSCRIPTION_ID=$(main-subscription-id)
        export ARM_TENANT_ID=$(tenant-id)
        terraform init \
          -backend-config="resource_group_name=rg-devops" \
          -backend-config="storage_account_name=satfstate98722" \
          -backend-config="container_name=cloudops-network-tfstate" \
          -backend-config="key=terraform.tfstate"
        terraform destroy -var="digicert_ssl_validation_key=$(digicert-ssl-validation-key)" -var="vpn_preshared_key=$(vpn-preshared-key)" --auto-approve
      displayName: Terraform init and destroy
      name: terraform_destroy
- stage: stop_aci
  displayName: Build Cleanup
  dependsOn:
  - terraform_apply
  - terraform_destroy
  condition: or(succeeded('terraform_apply'), succeeded('terraform_destroy'))
  pool:
    vmImage: ubuntu-latest
  jobs:
  - job: stop_aci
    displayName: Stop build agent
    steps:
    - task: AzureCLI@2
      displayName: Stop Azure Container Instance
      inputs:
        azureSubscription: 'terraform'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az container stop -n $(ACINAME) -g $(RGNAME)'